version: "2"

linters:
  enable:
    - revive
  settings:
    revive:
      rules:
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: if-return
        - name: increment-decrement
        - name: var-naming
        - name: var-declaration
        - name: receiver-naming
        - name: unexported-return
        - name: errorf
        - name: early-return
